### PR TITLE
Godot 4

### LINKED ISSUE #5: Update to Godot 4.0
This plugin looks awesome! I really like the simple design and easy to read infographics of your project work time. 

Will it ever be updated to work with Godot 4.0?

### PR DESCRIPTION
**Pull request by Fifut**
Update for Godot 4
Script adaptation
Tweek of some visual elements

_Closes https://github.com/YuriSizov/godot-time-tracker/issues/5_

### CODE REVIEW

**Comment by YuriSizov** [comment]
Sorry about the lack of response. I'll try to find some time to review this

**Comment by Fifut** [comment]
I think I made a mistake. I modified it (after update to Godot 4) to suit my use and I see that it appears here in this PR. Maybe I should have made a new repository for my modifications?

I didn't want to spoil your work

**Comment by YuriSizov** [comment]
@Fifut In general, you should create dedicated branches when working on PRs. This allows you to separate your work from your master branch. If you want, you can close this PR and open a new one from a different branch where only relevant changes would be

**Comment by Fifut** [comment]
Ok I will do that. Thank you

**Pull request closed without merging**
